# Generated by Django 2.2.7 on 2020-01-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='e-Rad公募情報のURL')),
                ('reference_number', models.CharField(max_length=200, unique=True, verbose_name='整理番号')),
                ('publishing_date', models.DateField(verbose_name='公開日')),
                ('funding_agency', models.CharField(max_length=200, verbose_name='配分機関')),
                ('call_for_applications', models.CharField(max_length=200, verbose_name='公募名')),
                ('application_unit', models.CharField(max_length=200, verbose_name='応募単位')),
                ('approved_institution', models.CharField(max_length=200, verbose_name='機関承認の有無')),
                ('opening_date', models.DateTimeField(verbose_name='受付開始日')),
                ('closing_date', models.DateTimeField(verbose_name='受付終了日')),
            ],
            options={
                'verbose_name': 'e-Rad公募情報',
                'verbose_name_plural': 'e-Rad公募情報',
            },
        ),
    ]
