# Generated by Django 2.2.7 on 2020-01-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erad', '0002_auto_20200119_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(unique=True, verbose_name='配分機関公募情報URL'),
        ),
    ]
