# Generated by Django 2.2.7 on 2020-01-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='財団等のURL')),
                ('jfc', models.URLField(blank=True, null=True, verbose_name='JFC URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('acceptance_date', models.DateField(verbose_name='受付日')),
                ('foundation', models.CharField(max_length=200, verbose_name='財団等の名称')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '研究資金公募情報',
                'verbose_name_plural': '研究資金公募情報',
            },
        ),
    ]
