# Generated by Django 2.2.7 on 2020-01-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='jfc',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='updated_at',
        ),
    ]
