# Generated by Django 2.2.11 on 2020-03-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0002_auto_20200124_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='grant_name',
            field=models.CharField(default=1, max_length=200, verbose_name='公募名'),
            preserve_default=False,
        ),
    ]
