# Generated by Django 2.2.11 on 2020-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0003_grant_grant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='url',
            field=models.TextField(blank=True, verbose_name='財団等のURL'),
        ),
    ]
