# Generated by Django 2.2.11 on 2020-03-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0005_grant_arrage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='arrage',
            new_name='arrange',
        ),
    ]
