# Generated by Django 2.2.11 on 2020-03-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0006_auto_20200323_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='arrange',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '必要')], verbose_name='取りまとめ'),
        ),
    ]
